/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface PatternConfig {
  'confidenceThreshold' : bigint,
  'patternName' : string,
  'enabled' : boolean,
  'symbol' : string,
}
export interface SignalHistoryEntry {
  'timeframe' : string,
  'patternName' : string,
  'timestamp' : Time,
  'confidence' : bigint,
  'symbol' : string,
  'signalType' : string,
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPatternConfigs' : ActorMethod<[], Array<PatternConfig>>,
  'getRecentSignalHistory' : ActorMethod<[bigint], Array<SignalHistoryEntry>>,
  'getSignalHistory' : ActorMethod<[], Array<SignalHistoryEntry>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'savePatternConfig' : ActorMethod<
    [string, string, boolean, bigint],
    undefined
  >,
  'saveSignalHistory' : ActorMethod<
    [string, string, string, string, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];