/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PatternConfig = IDL.Record({
  'confidenceThreshold' : IDL.Nat,
  'patternName' : IDL.Text,
  'enabled' : IDL.Bool,
  'symbol' : IDL.Text,
});
export const Time = IDL.Int;
export const SignalHistoryEntry = IDL.Record({
  'timeframe' : IDL.Text,
  'patternName' : IDL.Text,
  'timestamp' : Time,
  'confidence' : IDL.Nat,
  'symbol' : IDL.Text,
  'signalType' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPatternConfigs' : IDL.Func([], [IDL.Vec(PatternConfig)], ['query']),
  'getRecentSignalHistory' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(SignalHistoryEntry)],
      ['query'],
    ),
  'getSignalHistory' : IDL.Func([], [IDL.Vec(SignalHistoryEntry)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'savePatternConfig' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Bool, IDL.Nat],
      [],
      [],
    ),
  'saveSignalHistory' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PatternConfig = IDL.Record({
    'confidenceThreshold' : IDL.Nat,
    'patternName' : IDL.Text,
    'enabled' : IDL.Bool,
    'symbol' : IDL.Text,
  });
  const Time = IDL.Int;
  const SignalHistoryEntry = IDL.Record({
    'timeframe' : IDL.Text,
    'patternName' : IDL.Text,
    'timestamp' : Time,
    'confidence' : IDL.Nat,
    'symbol' : IDL.Text,
    'signalType' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPatternConfigs' : IDL.Func([], [IDL.Vec(PatternConfig)], ['query']),
    'getRecentSignalHistory' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(SignalHistoryEntry)],
        ['query'],
      ),
    'getSignalHistory' : IDL.Func([], [IDL.Vec(SignalHistoryEntry)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'savePatternConfig' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Bool, IDL.Nat],
        [],
        [],
      ),
    'saveSignalHistory' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };